
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jan 22 10:24:55 CET 2022
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
	public static final int NUMBER = 9;
	public static final int SEMI = 2;
	public static final int EOF = 0;
	public static final int ADD = 3;
	public static final int SUB = 4;
	public static final int DIV = 6;
	public static final int error = 1;
	public static final int RPAREN = 8;
	public static final int MUL = 5;
	public static final int LPAREN = 7;
	public static final int ASSIG = 11;
	public static final int IDENT = 12;

	static String vratiToken(int t){
		String s = "";
		switch (t){
		  case 12:
			s = "IDENTIFIER";
			break;
		  case 9:
			s = "NUMBER";
			break;
		  case 7:
			s = "LPAREN";
			break;
		  case 8:
			s = "RPAREN";
			break;
		  case 3:
			s = "ADD";
			break;
		  case 11:
			s = "ASSIG";
			break;
		  case 2:
			s = "SEMI";
			break;
		  case 0:
			s = "EOF";
			break;
		  case 5:
			s = "MULL";
			break;
		  default:
			s="";
		}
		return s;
	}
}

