
import java_cup.runtime.*;

action code
	{:
	static TabelaSimbola tabela = new TabelaSimbola();
	:};

/* Terminali */
terminal PLUS, MINUS, MUL, DIV, LPAREN, RPAREN, SEMI, ASSIG;
terminal Integer   NUMBER;
terminal String   IDENTIFAER;

/* Neterminali */
nonterminal Expr expr;
nonterminal Term term;
nonterminal Factor factor;
nonterminal Expr_part expr_part;
nonterminal expr_list;

/*gramatika */

expr_list ::= expr_list expr_part 
	      | 
              expr_part
              ;
              
expr_part ::= IDENTIFAER:id ASSIG expr:e SEMI
          {: 
          RESULT = new Expr_part(e); 
          TabelaSimbolaStavka stavka = new TabelaSimbolaStavka(id, "IDENTIFIER", ""+e.val);
	  tabela.dodaj(stavka);
	  Expr.kod = "";
          :}  
          ;
expr  ::= term:t   
          {: RESULT = new Expr(t); :} 
	  | 
	  expr:e PLUS term:t    
	  {: RESULT = new Expr(e, t); :} 
	  ;
term ::=  term:t MUL factor:f 
          {: RESULT = new Term(t,f); :} 
          |
          factor:f 
          {: RESULT = new Term(f); :}
          ;
factor::= LPAREN expr:e RPAREN
          {: RESULT = new Factor(e); :} 
          |
          NUMBER:n
          {: 
          RESULT = new Factor(n);  
          :}
          |
          IDENTIFAER:id
          {: 
          int val = tabela.pretrazi(id);
          RESULT = new Factor(id, val);  
          :};