
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Jan 30 10:26:12 CET 2022
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IDENTIFAER = 11;
  public static final int MINUS = 3;
  public static final int ASSIG = 9;
  public static final int NUMBER = 10;
  public static final int SEMI = 8;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int DIV = 5;
  public static final int error = 1;
  public static final int RPAREN = 7;
  public static final int MUL = 4;
  public static final int LPAREN = 6;
}

