
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jan 29 09:47:41 CET 2022
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IDENTIFAER = 11;
  public static final int ASSIG = 9;
  public static final int NUMBER = 10;
  public static final int SEMI = 2;
  public static final int EOF = 0;
  public static final int ADD = 3;
  public static final int SUB = 4;
  public static final int DIV = 6;
  public static final int error = 1;
  public static final int RPAREN = 8;
  public static final int MUL = 5;
  public static final int LPAREN = 7;
}

