
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Oct 30 08:27:57 CET 2022
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IDENTIFAER = 9;
  public static final int MINUS = 3;
  public static final int NUMBER = 8;
  public static final int SEMI = 7;
  public static final int EOF = 0;
  public static final int PLUS = 2;
  public static final int error = 1;
  public static final int RPAREN = 6;
  public static final int MUL = 4;
  public static final int LPAREN = 5;
}

